load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "batch_builder",
    srcs = ["batch_builder.cpp"],
    hdrs = ["batch_builder.h"],
    deps = ["//proto:metrics_cc_proto"],
)
