load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "agent_config",
    srcs = ["agent_config.cpp"],
    hdrs = ["agent_config.h"],
)
